# Kubernetes deployment for ai-preprocess
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hq-api
  namespace: mohiuddin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hq-api
  template:
    metadata:
      labels:
        app: hq-api
    spec:
      containers:
      - name: hq-api
        image: RedsopAcr.azurecr.io/image:09c36219ecf4d96b35e3c40de33d18312d08df84
        imagePullPolicy: Always
        
      imagePullSecrets:
      - name: acr-auth
