# Kubernetes deployment for ai-preprocess
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hq-api
  namespace: mohiuddin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hq-api
  template:
    metadata:
      labels:
        app: hq-api
    spec:
      containers:
      - name: hq-api
        image: RedsopAcr.azurecr.io/image:cf7b36e323fbe220e37af674ce269956a20f47bd
        imagePullPolicy: Always
        
      imagePullSecrets:
      - name: acr-auth
