apiVersion: apps/v1
kind: Deployment
metadata:
  name: hq-api
  namespace: mohiuddin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hq-api
  template:
    metadata:
      labels:
        app: hq-api
    spec:
      containers:
      - name: hq-api
        image: RedsopAcr.azurecr.io/image:10026dac8c1a775309c069a57ecb5ca2486eae33
        imagePullPolicy: Always
        
      imagePullSecrets:
      - name: acr-auth
